### ISSUE TITLE
Binary release?

### ISSUE THREAD

**Issue by andreabedini** [Kleidukos/print-api#12]
To be used effectively in CI it would be better to have a binary release. I am aware of the complications with respect to GHC compatibility but having an extra cabal build in CI in also fragile and expensive.

Can it be reduced to only boot dependencies so it can be invoke as a single script (a la runhaskell)

We can use the usual one-binary-per-ghc approach?

I apologise I haven't looked at the code yet, but I will soon!

**Comment by Kleidukos** [comment]
As explained in the REAMDE, releases provide binary artefacts. You can view them here: https://github.com/Kleidukos/print-api/releases/tag/v0.1.0.1

**Comment by andreabedini** [comment]
Crap, I looked and I didn't see them. I blame GitHub's mobile app.
