### ISSUE TITLE
print-api: cannot satisfy -package

### ISSUE THREAD

**Issue by jonkri** [Kleidukos/print-api#30]
Hi!

I'm trying to get print-api to work on my M1 MacBook Pro.

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.6.6
$ wget https://github.com/Kleidukos/print-api/releases/download/v0.1.0.1/print-api-0.1.0.1-macOS-9.6.6-arm64.tar.gz
$ tar xvvzf print-api-0.1.0.1-macOS-9.6.6-arm64.tar.gz
$ cabal update
$ cabal get text-display
$ cd text-display-0.0.5.2
$ ../print-api -p text-display
print-api: cannot satisfy -package text-display
    (use -v for more information)
```

`-v` can't be passed to `print-api`.

`cabal build` runs successfully in the `text-display` directory.

Any hints would be appreciated!

**Comment by jonkri** [comment]
Oh, this is embarrassing, I forgot to use `--write-ghc-environment-files=always` when running `cabal build`. It works now.

**Comment by Kleidukos** [comment]
Indeed, what you are seeing is a message from the GHC API that tells you to pass an option to the GHC binary (which doesn't exist, because we use the API directly).
